# Project Identity
spring.application.name=Foro-Hub-API
spring.profiles.active=dev

# Server Configuration
server.port=8080
server.error.include-stacktrace=never

# Database generic settings
spring.datasource.driver-class-name=org.postgresql.Driver
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Hibernate & JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Pagination (Clean JSON via DTO)
spring.data.web.pageable.serialization-mode=via-dto

# Flyway Migration
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# SpringDoc / OpenAPI (English documentation)
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html